### ISSUE TITLE
alpha-Gliadin (43-49) err

### ISSUE THREAD

**Issue by Ben3094** [SilentSpringInstitute/sdftosvg#3]
https://pubchem.ncbi.nlm.nih.gov/compound/130932

Exception has occurred: TypeError: Cannot read property 'type' of undefined
  at isCarbonBond (c:\Users\benja\ownCloud\Documents\Projects\GlumidiTag\Hardware design\Gluten solution\node_modules\sdftosvg\src\mol.js:124:31)
    at arrayFilter (c:\Users\benja\ownCloud\Documents\Projects\GlumidiTag\Hardware design\Gluten solution\node_modules\lodash\lodash.js:596:11)
    at Function.filter (c:\Users\benja\ownCloud\Documents\Projects\GlumidiTag\Hardware design\Gluten solution\node_modules\lodash\lodash.js:9241:14)
    at findCycles (c:\Users\benja\ownCloud\Documents\Projects\GlumidiTag\Hardware design\Gluten solution\node_modules\sdftosvg\src\mol.js:183:19)
    at computeAromaticCenters (c:\Users\benja\ownCloud\Documents\Projects\GlumidiTag\Hardware design\Gluten solution\node_modules\sdftosvg\src\mol.js:89:12)
    at parseMol (c:\Users\benja\ownCloud\Documents\Projects\GlumidiTag\Hardware design\Gluten solution\node_modules\sdftosvg\src\mol.js:289:3)
    at Object.module.exports.renderSdfToSvg (c:\Users\benja\ownCloud\Documents\Projects\GlumidiTag\Hardware design\Gluten solution\node_modules\sdftosvg\index.js:12:18)
    at c:\Users\benja\ownCloud\Documents\Projects\GlumidiTag\Hardware design\Gluten solution\node_modules\sdftosvg\index.js:35:20
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
    at FSReqCallback.callbackTrampoline (internal/async_hooks.js:131:14)

**Comment by Ben3094** [comment]
@ntr-808
